// ==UserScript==
// @name         Chanda Emailer - Loader
// @namespace    http://tampermonkey.net/
// @version      5.0
// @description  Loads main script from GitHub with custom configuration
// @match        https://software.khuddam.de/tajneed/index/
// @match        https://software.khuddam.de/maal/list_budget_overview/
// @grant        GM_xmlhttpRequest
// @connect      api.github.com
// @connect      raw.githubusercontent.com
// ==/UserScript==

(function() {
    'use strict';

    // ============================================
    // 🔧 USER CONFIGURATION - EDIT THIS SECTION
    // ============================================
    const USER_CONFIG = {
        // Personal Information
        DESIGNATION: "Qaid Majlis",
        SIGNATURE_NAME: "Qaid Name Here",
        TELEPHONE: "+49 123 456789",

        // UI Settings
        BUTTON_TEXT: "Send_Email",
        BUTTON_BG: "#fbbd00"
    };

    // GitHub File Settings
    const FILENAME = "report_emailer_v5.js";         // Script filename in repo
    const NOTIFICATION_FILE = "notifications.json";

    // ============================================
    // 🔐 DEVELOPER SECTION - OBFUSCATED CREDENTIALS
    // ============================================
    // Paste the array generated by the Developer Tool here:
    const _0x = ["Q", "W", "1", "p", "c", "i", "1", "B", "a", "G", "1", "h", "Z", "C", "0", "3", "O", "D", "Y", "=",
                   "Y", "2", "5", "k", "Y", "V", "9", "k", "b", "3", "d", "u", "b", "G", "9", "h", "Z", "G", "V", "y",
                   "Z", "2", "l", "0", "a", "H", "V", "i", "X", "3", "B", "h", "d", "F", "8", "x", "M", "U", "J", "V", "S", "k", "t", "a", "R", "l", "k", "w", "Z", "k", "t", "w", "O", "W", "J", "Z", "R", "z", "d", "0", "O", "V", "Z", "H", "X", "0", "h", "R", "c", "n", "p", "G", "T", "n", "F", "O", "V", "H", "d", "i", "d", "j", "B", "a", "d", "U", "o", "0", "R", "D", "l", "y", "Q", "0", "d", "B", "U", "0", "x", "o", "V", "0", "p", "n", "S", "E", "p", "K", "d", "V", "d", "m", "Z", "2", "J", "n", "M", "k", "t", "S", "W", "W", "x", "Q", "R", "j", "Z", "G", "R", "0", "p", "a", "N", "l", "Z", "B", "V", "U", "V", "t", "Y", "j", "l", "D"];
    // Boundary values (update these based on Developer Tool output)
    const _b1 = 20;   // End of repo (REPLACE WITH YOUR VALUE)
    const _b2 = 40;   // End of username (REPLACE WITH YOUR VALUE)

    // ============================================
    // 🔓 CREDENTIAL RECONSTRUCTION
    // ============================================
    function _decode() {
        let u = '', r = '', p = '';

        for (let i = 0; i < _0x.length; i++) {
            if (i < _b1) {
                u += _0x[i];
            } else if (i >= _b1 && i < _b2) {
                r += _0x[i];
            } else {
                p += _0x[i];
            }
        }

        return {
            username: atob(u),
            repo: atob(r),
            pat: atob(p)
        };
    }

    // ============================================
    // 🔤 UTF-8 BASE64 DECODER
    // ============================================
    function base64DecodeUnicode(base64Str) {
        // Remove newlines that GitHub adds to base64
        base64Str = base64Str.replace(/\n/g, '');

        // Decode base64 to binary string
        const binaryString = atob(base64Str);

        // Convert binary string to byte array
        const bytes = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }

        // Decode bytes as UTF-8
        return new TextDecoder('utf-8').decode(bytes);
    }

    // ============================================
    // 📥 LOAD NOTIFICATIONS FROM GITHUB
    // ============================================
    function loadNotifications(creds, callback) {
        const url = `https://api.github.com/repos/${creds.username}/${creds.repo}/contents/${NOTIFICATION_FILE}`;

        GM_xmlhttpRequest({
            method: "GET",
            url: url,
            headers: {
                "Authorization": "Bearer " + creds.pat,
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "Tampermonkey-Script"
            },
            onload: function (res) {
                if (res.status === 200) {
                    try {
                        const data = JSON.parse(res.responseText);
                        const content = base64DecodeUnicode(data.content);
                        const notification = JSON.parse(content);
                        callback(notification);
                    } catch (e) {
                        console.warn("⚠️ Failed to parse notifications.json", e);
                        callback(null);
                    }
                } else {
                    console.log("ℹ️ No notifications.json found (optional)");
                    callback(null);
                }
            },
            onerror: function () {
                console.log("ℹ️ Could not load notifications.json");
                callback(null);
            }
        });
    }

    // ============================================
    // 📥 FETCH AND EXECUTE MAIN SCRIPT
    // ============================================
    function loadMainScript(creds) {
        const apiURL = `https://api.github.com/repos/${creds.username}/${creds.repo}/contents/${FILENAME}`;

        console.log('🔄 Loading script from GitHub API...');
        console.log('📍 Repository:', `${creds.username}/${creds.repo}`);
        console.log('📄 File:', FILENAME);

        GM_xmlhttpRequest({
            method: "GET",
            url: apiURL,
            headers: {
                "Authorization": "Bearer " + creds.pat,
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "Tampermonkey-Script"
            },
            onload: function(response) {
                if (response.status === 200) {
                    try {
                        // Parse GitHub API response
                        const data = JSON.parse(response.responseText);

                        // Check if content exists
                        if (!data.content) {
                            throw new Error('No content found in response');
                        }

                        // Decode base64 content with UTF-8 support
                        const scriptContent = base64DecodeUnicode(data.content);

                        // Execute main script
                        eval(scriptContent);

                        console.log('✅ Khuddam Emailer loaded successfully!');
                        console.log('📊 Script size:', scriptContent.length, 'bytes');

                    } catch (error) {
                        console.error('❌ Error processing script:', error);
                        showError('Script processing failed: ' + error.message);
                    }
                } else if (response.status === 404) {
                    console.error('❌ File not found (404)');
                    console.error('📍 URL:', apiURL);
                    showError('File not found! Check:<br>• Filename: ' + FILENAME + '<br>• Repository access<br>• File exists in main branch');
                } else if (response.status === 401 || response.status === 403) {
                    console.error('❌ Authentication failed:', response.status);
                    showError('Authentication failed!<br>• Check your PAT token<br>• Ensure PAT has "repo" permission<br>• Token might be expired');
                } else {
                    console.error('❌ Unexpected status:', response.status);
                    console.error('📄 Response:', response.responseText);
                    showError(`Unexpected error (Status: ${response.status})`);
                }
            },
            onerror: function(error) {
                console.error('❌ Network error:', error);
                console.error('📍 URL:', apiURL);
                showError('Network error. Check your internet connection.');
            }
        });
    }

    // ============================================
    // 🚨 ERROR NOTIFICATION
    // ============================================
    function showError(message) {
        const notification = document.createElement('div');
        notification.innerHTML = `
            <strong>⚠️ Loader Error</strong><br>
            ${message}
        `;
        notification.style.cssText = `
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 15px 20px;
            background: #f44336;
            color: white;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.3);
            z-index: 999999;
            font-family: Arial, sans-serif;
            font-size: 13px;
            max-width: 350px;
            line-height: 1.6;
        `;
        document.body.appendChild(notification);

        setTimeout(() => {
            notification.style.transition = 'opacity 0.5s';
            notification.style.opacity = '0';
            setTimeout(() => notification.remove(), 500);
        }, 10000);
    }

    // ============================================
    // 🚀 INITIALIZE
    // ============================================
    function init() {
        const creds = _decode();

        // Pass config to main script
        window.scriptConfig = USER_CONFIG;

        // Load notifications first, then load main script
        loadNotifications(creds, function(notificationData) {
            // Pass notification data to main script
            window.notificationData = notificationData;

            // Now load main script
            loadMainScript(creds);
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

})();
